package com.microsoft.spark.insight.cli

import com.microsoft.spark.insight.cli.frontend._

/**
 * An interface to be implemented by varieties of Spark Perf analysis report which have both Text and Html Reports
 *
 * @tparam T the type of Spark id collection
 */
trait ReportCli[T <: AppIdSets] extends TextReport[T] with HtmlReport[T]

/**
 * ReportCli companion object to maintain constants centrally
 */
object ReportCli {

  /**
   * Let users pay attention to terminal width
   *
   * @return message to warn users.
   */
  def firstLineNote: String =
    "Note: Expanding the terminal window may be necessary for viewing the report properly.".bold.underlined

  /**
   * Notify users about Html Version of the report.
   *
   * @return message to notify users.
   */
  def htmlNote: String =
    ("\nNote: An interactive HTML version of this report can be generated by specifying " +
      "\"-H\" when running GridBench\n").yellow
}
